name: Build
on:
  push:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/
          ~/.cargo/git/db/
          target/
          ~/.rustup
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
    - name: rust latest stable
      run: rustup install stable && rustup default stable
    - name: upx
      run: >
        curl -L --get https://github.com/upx/upx/releases/download/v4.1.0/upx-4.1.0-amd64_linux.tar.xz
        | tar -xJOf - upx-4.1.0-amd64_linux/upx > upx
        && chmod +x upx
        && sha256sum upx
        | grep 76bc250b88595cdf92d9ea853c402d0345178a0d32a12cb2a4850d9bd079cd19
    - run: cargo build --release --locked
    - name: compressing
      run: >
        cp target/release/swc-minifier .
        && strip -s swc-minifier
        && ./upx swc-minifier
        && chmod +x swc-minifier
    - uses: actions/upload-artifact@v3
      with:
        name: swc-minifier
        path: swc-minifier
